### ISSUE TITLE
Test HMD tracking in non-maingame situations

### ISSUE THREAD

**Issue by philhzss** [fordcars/OttoMatic-VR#28]
HMD (camera tracking works in game, but does not / has not been tested in:
- [ ] Main menu, all main menu items 
- [ ]  Cutscenes, win scene, end scene
  - They seem to be tilted oddly, but tracking works
- [ ] Rocket leaving-world scene
- ~~Saucer level~~ Will be its own separate issue one day

**Comment by philhzss** [comment]
Handle all of the rewriting in issue #30, it's basically the same thing. If we get the camera tracking system done properly it will automatically work everywhere, might need to tweak it a lot for Level 9. I'll keep this issue for testing
